### ISSUE TITLE
Incorrect values written

### ISSUE THREAD

**Issue by fami-com** [147loch/terraria-world-difficulty-changer#1]
Hello, I've tried to use your tool, but it didn't work, so I checked your code and you seem to be setting the difficulty to master (2) regardless of the actually selected option (line 170). And you're also always enabling hardmode (line 172). Additionally, the most current version is now 226 (1.4.0.2).

**Comment by Lutonite** [comment]
Thanks for reporting it! I hope you had a backup of your world file.
I was doing this at 3AM last night, so now I know I shouldn't be up late coding stuff.

Commit e5b7cb449cad48f64e27a2e91d6bee400322b88e should fix this issue.
I've hotpatched the release to 1.0.0.3. Thanks again!
